### PR TITLE
build: build for python 3.9

### PR DESCRIPTION
**Pull request by Jim-Holmstroem**

### CODE REVIEW

**Review by samedii — APPROVED** [review]

**Comment by Jim-Holmstroem** [comment]
blocked by #53

**Comment by samedii** [comment]
Rebase and it will build

**Comment by samedii** [comment]
Seems like we have a new error. Version 3.9 is failing now instead

**Comment by Jim-Holmstroem** [comment]
blocked by https://github.com/pytorch/pytorch/issues/45731

**Pull request merged**
